provider-iam:
  - Effect: Allow
    Action:
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:DescribeTable
    Resource:
      - ${self:custom.profiles-service-table.arn}
    #   - !Join ["/", ["${self:custom.dive-diver-table.arn}", "index", "orderBy"]]
  - Effect: 'Allow'
    Action:
      - lambda:InvokeFunction # Permission for Lambda invoke warmup function
      - lambda:listAliases
      - lambda:listVersionsByFunction
      - lambda:deleteFunction
      - lambda:listLayerVersions
      - lambda:deleteLayerVersion
    Resource: '*'
