logbook-bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.logbook-bucket.name}
    LifecycleConfiguration:
      Rules:
        - Id: ExpirePictures
          Status: Enabled
          ExpirationInDays: 1

logbook-bucket-policy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref LogbookBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.logbook-bucket.name}/*
