diving-diver-table:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: diving-diver-table-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
    BillingMode: PAY_PER_REQUEST
    Tags:
      - Key: Name
        Value: diving-diver-table
      - Key: createdBy
        Value: SeanKnowles
