service: logbook-service
app: opsap
org: opsap

configValidationMode: error

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    DIVE_DIVER_TABLE: ${self:custom.diveDiverTable.name}
  # DIVE_SUPERVISOR_TABLE: ${self:custom.diveSupervisorTable.name}
  iam:
    role:
      statements: ${file(resources/diver/diveDiverTableIAM.yml):diveDiverTableIAM}

resources:
  Resources:
    diveDiverTable: ${file(resources/diver/diveDiverTable.yml):diveDiverTable}
  # diveSupervisorTable: ${file(resources/supervisor/diveSupervisorTable.yml):diveDiverTable}

functions:
  createDive:
    handler: src/handlers/createDive.handler
    description: 'log a dive'
    events:
      - http:
          method: POST
          path: /dive

  getDives:
    handler: src/handlers/getDives.handler
    events:
      - http:
          method: GET
          path: /dive

  getDive:
    handler: src/handlers/getDive.handler
    events:
      - http:
          method: GET
          path: /dive/{id}

  updateDive:
    handler: src/handlers/updateDive.handler
    events:
      - http:
          method: PATCH
          path: dive/{id}

  deleteDive:
    handler: src/handlers/deleteDive.handler
    events:
      - http:
          method: DELETE
          path: dive/{id}

  #processAuctions:
  #handler: src/handlers/processAuctions.handler
  # events:
  #   - schedule: rate(1 minute)

custom:
  diveDiverTable:
    name: !Ref diveDiverTable
    arn: !GetAtt diveDiverTable.Arn
  bundle:
    linting: true
