service: logbook-service
app: opsap
org: opsap

configValidationMode: error

plugins:
  - serverless-esbuild
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iam:
    role:
      statements: ${file(resources/aws/diveDiverTableIAM.yml):diveDiverTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/aws/diveDiverTable.yml):diveDiverTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    description: 'creates an auction'
    events:
      - http:
          method: POST
          path: /auction

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid

  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    #   - schedule: rate(1 minute)

custom:
  AuctionsTable:
    name: !Ref diveDiverTable
    arn: !GetAtt diveDiverTable.Arn
  bundle:
    linting: true
