provider-iam:
  - Effect: 'Allow'
    Action:
      - lambda:InvokeFunction # Permission for Lambda invoke warmup function
      - lambda:listAliases
      - lambda:listVersionsByFunction
      - lambda:deleteFunction
      - lambda:listLayerVersions
      - lambda:deleteLayerVersion
    Resource: '*'
