logbook-service-table:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-${self:provider.stage}-table
    AttributeDefinitions:
      - AttributeName: PK # userId
        AttributeType: S
      - AttributeName: SK # entryId
        AttributeType: S
      - AttributeName: logbook
        AttributeType: S
      - AttributeName: company
        AttributeType: S
      - AttributeName: clientRep
        AttributeType: S
      - AttributeName: country
        AttributeType: S
      - AttributeName: entryType #(air or saturation)
        AttributeType: S
      - AttributeName: primaryCat #(inshore or offshore)
        AttributeType: S
      - AttributeName: secondaryCat #(construction/inspection/salvage)
        AttributeType: S
      - AttributeName: verifierId
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
      - AttributeName: GSK1
        AttributeType: S
      - AttributeName: GSK2
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: userId-index
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: entriesId-index
        KeySchema:
          - AttributeName: SK
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: GSK1-index
        KeySchema:
          - AttributeName: GSK1
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: GSK2-index
        KeySchema:
          - AttributeName: GSK2
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: verifierId-index
        KeySchema:
          - AttributeName: verifierId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: logbook-index
        KeySchema:
          - AttributeName: logbook
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: company-index
        KeySchema:
          - AttributeName: company
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: clientRep-index
        KeySchema:
          - AttributeName: clientRep
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: country-index
        KeySchema:
          - AttributeName: country
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: entryType-index
        KeySchema:
          - AttributeName: entryType
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: primaryCat-index
        KeySchema:
          - AttributeName: primaryCat
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: secondaryCat-index
        KeySchema:
          - AttributeName: secondaryCat
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: createdAt-index
        KeySchema:
          - AttributeName: createdAt
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    Tags:
      - Key: created-by
        Value: 'Sean Knowles'
