service: client-web
app: opsap
org: opsap

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline # Enables local devleopment
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-plugin-warmup # Keeps function warmed up, no cold starts
  - serverless-prune-plugin # Prune old functions

useDotenv: true
configValidationMode: error
package: # Packages functions individually
  individually: true
