diveDiverTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: diveDiverTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: "_ID"
        AttributeType: "S"
      - AttributeName: "createdAt"
        AttributeType: "S"
      - AttributeName: "userId"
        AttributeType: "S"
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: "_ID"
        KeyType: "HASH"
      - AttributeName: "createdAt"
        KeyType: "RANGE"
    GlobalSecondaryIndexes:
      - IndexName: "byOrder"
        KeySchema:
          - AttributeName: "userId"
            KeyType: "HASH"
          - AttributeName: "createdAt"
            KeyType: "RANGE"
        Projection:
          ProjectionType: ALL #return all results
    Tags:
      - Key: Name
        Value: dive-diver-table
