service: profiles-service
app: opsap
org: opsap

## test test

plugins:
  - serverless-esbuild
  - serverless-offline # Enables local devleopment
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-plugin-warmup # Keeps function warmed up, no cold starts
  - serverless-prune-plugin # Prune old functions
  - serverless-seed
  - serverless-domain-manager

useDotenv: true
configValidationMode: error
package: # Packages functions individually
  individually: true

custom:
  customDomain:
    domainName: api.opsap.com
    basePath: 'logbook'
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: edge
  esbuild:
    packager: yarn
    bundle: true
    minify: true
  seed: # CICD plugin to stop full re-deployments when updating non essential files
    incremental:
      enabled: true
      disabledFor:
        - prod
        - staging
  prune:
    automatic: true
    includeLayers: true
    number: 3
  profiles-service-table:
    name: !Ref ProfilesServiceTable
    arn: !GetAtt ProfilesServiceTable.Arn
  bundle:
    linting: true
  warmup:
    default:
      enabled: true
      folderName: '.warmup'
      concurrency: 1
      # prewarm: true
      schedule: rate(5 minutes)
      sourceRaw: true
      timeout: 60
      memorySize: 128
      name: ${self:service}-${self:provider.stage}-warmer-default
      package:
        individually: true
      tags:
        Project: opsap
        createdBy: Sean Knowles

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    PROFILES_SERVICE_TABLE: ${self:custom.profiles-service-table.name}
  iam:
    role:
      statements: ${file(infra/provider-iam.yml):provider-iam}

resources:
  Resources:
    ProfilesServiceTable: ${file(infra/profiles-service-table.yml):profiles-service-table}

functions:
  ########## User
  user-create-profile:
    handler: functions/user/create-profile.handler
    name: ${self:service}-${self:provider.stage}-user-create-profile
    description: 'create user profile'
    warmup:
      default:
        enabled:
          # - dev
          # - prod
    events:
      - http:
          method: POST
          path: user/create-profile
          cors: true

  user-get-profiles:
    handler: functions/user/get-profiles.handler
    name: ${self:service}-${self:provider.stage}-user-get-profiles
    description: 'get all user profiles'
    warmup:
      default:
        enabled:
          # - dev
          # - prod
    events:
      - http:
          method: GET
          path: user/get-profiles/{userId}
          cors: true

  user-get-profile:
    handler: functions/user/get-profile.handler
    name: ${self:service}-${self:provider.stage}-user-get-profile
    description: 'get user profile'
    warmup:
      default:
        enabled:
          # - dev
          # - prod
    events:
      - http:
          method: GET
          path: user/get-profile/{userId}/{profileId}
          cors: true

  user-update-profile:
    handler: functions/user/update-profile.handler
    name: ${self:service}-${self:provider.stage}-user-update-profile
    description: 'update user profile'
    warmup:
      default:
        enabled:
          # - dev
          # - prod
    events:
      - http:
          method: PATCH
          path: user/update-profile/{userId}
          cors: true

  user-delete-profile:
    handler: functions/user/delete-profile.handler
    name: ${self:service}-${self:provider.stage}-user-delete-profile
    description: 'delete user profile'
    warmup:
      default:
        enabled:
          # - dev
          # - prod
    events:
      - http:
          method: DELETE
          path: user/delete-profile/{userId}/{profileId}
          cors: true

  ########## Company
  company-create-profile:
    handler: functions/company/create-profile.handler
    name: ${self:service}-${self:provider.stage}-company-create-profile
    description: 'create company profile'
    warmup:
      default:
        enabled:
          # - dev
          # - prod
    events:
      - http:
          method: POST
          path: company/create-profile
          cors: true
