dynamodb-table:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-${self:provider.stage}-table
    AttributeDefinitions:
      - AttributeName: PK #userId
        AttributeType: S
      - AttributeName: SK #postId
        AttributeType: S
      - AttributeName: category
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: postId-index
        KeySchema:
          - AttributeName: SK
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: category-index
        KeySchema:
          - AttributeName: category
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: createdAt-index
        KeySchema:
          - AttributeName: createdAt
            KeyType: HASH
        Projection:
          ProjectionType: ALL
