diveDiverTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: diveDiverTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: '_ID'
        AttributeType: 'S'
      - AttributeName: 'userId'
        AttributeType: 'S'
      - AttributeName: 'supervisorName'
        AttributeType: 'S'
      - AttributeName: 'supervisorEmail'
        AttributeType: 'S'
      - AttributeName: 'companyName'
        AttributeType: 'S'
      - AttributeName: 'companyAddress'
        AttributeType: 'S'
      - AttributeName: 'location'
        AttributeType: 'S'
      - AttributeName: 'type'
        AttributeType: 'S'
      - AttributeName: 'maximumDepth'
        AttributeType: 'S'
      - AttributeName: 'leftSurfaceAt'
        AttributeType: 'S'
      - AttributeName: 'totalBottomTime'
        AttributeType: 'S'
      - AttributeName: 'decoCompletedAt'
        AttributeType: 'S'
      - AttributeName: 'diveTable'
        AttributeType: 'S'
      - AttributeName: 'breathingMixture'
        AttributeType: 'S'
      - AttributeName: 'equipmentUsed'
        AttributeType: 'S'
      - AttributeName: 'diveDescription'
        AttributeType: 'S'
      - AttributeName: 'createdAt'
        AttributeType: 'S'
      - AttributeName: 'updatedAt'
        AttributeType: 'S'
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: '_ID'
        KeyType: 'HASH'
      - AttributeName: 'createdAt'
        KeyType: 'RANGE'
    GlobalSecondaryIndexes:
      - IndexName: 'byOrder'
        KeySchema:
          - AttributeName: 'userId'
            KeyType: 'HASH'
          - AttributeName: 'createdAt'
            KeyType: 'RANGE'
        Projection:
          ProjectionType: ALL #return all results
    Tags:
      - Key: Name
        Value: dive-diver-table
