service: auth-service
app: opsap
org: opsap

plugins:
  - serverless-bundle
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  memorySize: 512
  environment:
    AUTH0_PUBLIC_KEY: ${file(dev-opsap.pem)}

functions:
  my-auth-guard-func:
    handler: functions/auth.handler
    events:
      - http:
          path: auth
          method: post
          cors: true
  public-endpoint:
    handler: functions/public.handler
    events:
      - http:
          path: auth/public
          method: POST
          # authorizer: my-auth-guard-func # public until authorizer is uncommented
          cors: true
  private-endpoint:
    handler: functions/private.handler
    events:
      - http:
          path: auth/private
          method: POST
          authorizer: my-auth-guard-func
          cors: true

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.opsap.com
    staging: staging-api.opsap.com
    dev: dev-api.opsap.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: auth
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: edge
  bundle:
    linting: true
